INSERT INTO player (name) VALUES ('Stine');
INSERT INTO player (name) VALUES ('Emily');
INSERT INTO player (name) VALUES ('Alex');
INSERT INTO player (name) VALUES ('Karina');
INSERT INTO player (name) VALUES ('Mike');
INSERT INTO player (avatar_name) VALUES ('Navier');
INSERT INTO player (avatar_name) VALUES ('Ervyn');
INSERT INTO player (avatar_name) VALUES ('Smorgasbord');
INSERT INTO player (avatar_name) VALUES ('Ganna');
INSERT INTO player (avatar_name) VALUES ('Sildriel');
INSERT INTO location (region_name, city_area, housing) VALUES ('Swords Coast', 'Baldurs Gate', 'Purple Wyrm Inn');
INSERT INTO location (region_name, city_area, housing) VALUES ('Swords Coast', 'Cloak Wood', 'Camp');
INSERT INTO location (region_name, city_area, housing) VALUES ('Under Dark', 'Phalorm', 'Old Ruins');
INSERT INTO location (region_name, city_area, housing) VALUES ('Icewind Dale', 'Bryn Shander', 'Faelfarils Inn');
INSERT INTO location (region_name, city_area, housing) VALUES ('Swords Coast', 'Daggerford', 'Ducal Castle');
